### ISSUE TITLE
sass-lint error on recent 2017.3 EAP releases

### ISSUE THREAD

**Issue by narration-sd** [idok/sass-lint-plugin#20]
This is kind of weirdly-acting. I get a red-letter IDE Error toast every time opening build 173.3415.21 (and I _think_ previous one also, but recently, anyway.  This goes away in not many seconds, if it remains in the logs. If I click it in time, I get informed about you, with the  stack trace below.

This doesn't happen on sccs-lint; it's clean. So should be an easy find, would think. I looked through the .idea and main WebStorm config files; didn't see any double representations of sass-lint, though possibly that's because the problem resides in a binary db file. Uninstall/Reinstall didn't help in any way -- cheers.

Short name 'SassLintInspection' is not unique
class 'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
and
class'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
conflict [Plugin: com.wix.sasslint]
com.intellij.diagnostic.PluginException: Short name 'SassLintInspection' is not unique
class 'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
and
class'com.sasslint.inspection.SassLintInspection' in PluginDescriptor[name='Sass Lint', classpath='C:\Users\narra\.PhpStorm2017.3\config\plugins\sass-lint-plugin']
conflict [Plugin: com.wix.sasslint]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by willydee** [comment]
Confirmed, getting the same message in WebStorm.
```
WebStorm 2017.3 EAP
Build #WS-173.3531.1, built on October 31, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-16-generic (Ubuntu 17.10)
```
