### ISSUE TITLE
Incomplete config panel in project Default Prefs window

### ISSUE THREAD

**Issue by fburleigh** [idok/sass-lint-plugin#8]
I believe Sass Lint is having trouble with IDE 2016.2 EAP. The plugin is installed, but I've seen the IDE have trouble running it -- could be node or sass-lint config paths get lost (see stack trace below). I have the latest Node and sass-lint, and have configured paths to them under IDE's Preferences window, Other Settings, Sass Lint.

Additionally, Sass Lint in a project doesn't show a config panel (the panel reads "Select a configuration element...") which means you cannot provide the path to a local .sass-config.yml file.

>Cannot create configurable component: Argument for @NotNull parameter 'cwd' of com/wix/nodejs> /NodeRunner.createCommandLine must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'cwd' of com/wix/nodejs/NodeRunner.createCommandLine must not be null
	at com.wix.nodejs.NodeRunner.createCommandLine(NodeRunner.java)
	at com.sasslint.cli.SassLintRunner.createCommandLine(SassLintRunner.java:99)
	at com.sasslint.cli.SassLintRunner.version(SassLintRunner.java:79)
	at com.sasslint.cli.SassLintRunner.runVersion(SassLintRunner.java:90)
	at com.sasslint.settings.SassLintSettingsPage.getVersion(SassLintSettingsPage.java:185)
	at com.sasslint.settings.SassLintSettingsPage.validate(SassLintSettingsPage.java:165)
	at com.sasslint.settings.SassLintSettingsPage.update(SassLintSettingsPage.java:126)
	at com.sasslint.settings.SassLintSettingsPage.access$300(SassLintSettingsPage.java:39)
	at com.sasslint.settings.SassLintSettingsPage$4.run(SassLintSettingsPage.java:119)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2414)
	at com.sasslint.settings.SassLintSettingsPage.updateLaterInEDT(SassLintSettingsPage.java:117)
	at com.sasslint.settings.SassLintSettingsPage.access$200(SassLintSettingsPage.java:39)
	at com.sasslint.settings.SassLintSettingsPage$3.textChanged(SassLintSettingsPage.java:103)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
	at javax.swing.plaf.basic.BasicComboBoxEditor$BorderlessTextField.setText(BasicComboBoxEditor.java:144)
	at com.intellij.ui.TextFieldWithHistory.setText(TextFieldWithHistory.java:77)
	at com.sasslint.settings.SassLintSettingsPage.loadSettings(SassLintSettingsPage.java:293)
	at com.sasslint.settings.SassLintSettingsPage.createComponent(SassLintSettingsPage.java:249)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:71)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:771)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:454)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1651)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1593)
	at com.intellij.openapi.options.newEditor.SettingsDialog.access$101(SettingsDialog.java:41)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:77)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.a(MacOSApplicationProvider.java:141)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ogonkov** [comment]
Same here, couldn't use plugin without access to settings, only sign "Select a configuration element..." without any inputs.

WebStorm 2016.1.3
Build #WS-145.1616, built on May 27, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
