### ISSUE TITLE
Error "cannot create configurable component: path doesn't exist"

### ISSUE THREAD

**Issue by maggo** [idok/sass-lint-plugin#9]
Plugin crashes at startup, PHPStorm version 2016.2 EAP

```
cannot create configurable component: path doesn't exist
java.lang.IllegalArgumentException: path doesn't exist
	at com.wix.nodejs.NodeRunner.createCommandLine(NodeRunner.java:40)
	at com.sasslint.cli.SassLintRunner.createCommandLine(SassLintRunner.java:99)
	at com.sasslint.cli.SassLintRunner.version(SassLintRunner.java:79)
	at com.sasslint.cli.SassLintRunner.runVersion(SassLintRunner.java:90)
	at com.sasslint.settings.SassLintSettingsPage.getVersion(SassLintSettingsPage.java:185)
	at com.sasslint.settings.SassLintSettingsPage.validate(SassLintSettingsPage.java:165)
	at com.sasslint.settings.SassLintSettingsPage.update(SassLintSettingsPage.java:126)
	at com.sasslint.settings.SassLintSettingsPage.access$300(SassLintSettingsPage.java:39)
	at com.sasslint.settings.SassLintSettingsPage$4.run(SassLintSettingsPage.java:119)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2397)
	at com.sasslint.settings.SassLintSettingsPage.updateLaterInEDT(SassLintSettingsPage.java:117)
	at com.sasslint.settings.SassLintSettingsPage.access$200(SassLintSettingsPage.java:39)
	at com.sasslint.settings.SassLintSettingsPage$3.textChanged(SassLintSettingsPage.java:103)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
	at javax.swing.plaf.basic.BasicComboBoxEditor$BorderlessTextField.setText(BasicComboBoxEditor.java:144)
	at com.intellij.ui.TextFieldWithHistory.setText(TextFieldWithHistory.java:77)
	at com.sasslint.settings.SassLintSettingsPage.loadSettings(SassLintSettingsPage.java:291)
	at com.sasslint.settings.SassLintSettingsPage.createComponent(SassLintSettingsPage.java:249)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:71)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel$1.compute(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:866)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:65)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:70)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:67)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:88)
	at com.intellij.ui.CardLayoutPanel.b(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.a(CardLayoutPanel.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:777)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:454)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.options.newEditor.SettingsDialog.access$101(SettingsDialog.java:41)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:77)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.a(MacOSApplicationProvider.java:137)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by wawyed** [comment]
Same issue here on Webstorm 2016.2  (Linux mint 18)

**Comment by todd-richmond** [comment]
this broke in 1.0.2 on IntelliJ. 1.0.1 did not crash, though it didn't seem to use my yml settings

**Comment by todd-richmond** [comment]
broke in 1.0.2 - manually installing 1.0.1 prevents the path problem

**Comment by D34THWINGS** [comment]
@idok @dmnplb any ideas how to fix this ?

Seems like when the path to node interpreter is empty it makes the plugin crash. Something bugs me out though [here](https://github.com/idok/sass-lint-plugin/blob/master/src/com/sasslint/settings/SassLintSettingsPage.java#L164). The plugins tries to get the version if validator has errors and that can't success because if path to node interpreter is empty validator will fail but get the version nonetheless and make the plugin crash since path to node interpreter is [mandatory](https://github.com/idok/intellij-common/blob/master/src/com/wix/nodejs/NodeRunner.java#L39) for the `getVersion` function to work. 

Since i don't know how to setup properly my environment to debug things myself, i need someone to test out what happens if you put a `!` in that condition. Or if someone can explain how dependencies for plugin works, how to import them into my IntelliJ Community Edition as the builder throws me that the `com.wix.nodejs` package is missing.
